---
- name: Create VLAN on AsterNOS switches
  hosts: astonos_switches
  gather_facts: no

  tasks:
    - name: Enter CLI and Apply VLAN Configuration
      # The key 'ansible.builtin.raw:' is at 4 spaces
      ansible.builtin.raw: |
        # All lines below the '|' must be indented (e.g., 6 spaces total)
        ENTRY_CMD
        configure terminal
        vlan 1000
        description Test
        end
       # write memory
